package dk.mallingbio.domain.state;

public enum ScreenEvent {
    NEXT_SHOW_WINDOW_OPENED,
    PUBLIC_START_REACHED,

    MANUAL_START_REQUESTED,
    MANUAL_DELAY_REQUESTED,
    MANUAL_EARLY_START_REQUESTED,

    SHOW_PAUSED_AFTER_START,
    CURRENT_CONTENT_IS_TRAILER,
    CURRENT_CONTENT_IS_FEATURE,
    START_FAILED,

    DOOR_REMINDER_REACHED,
    MANUAL_DOORS_CONFIRMED,
    SHOW_FINISHED,
    PREPARE_NEXT_COMPLETED
}